# Generated by Django 4.2.28 on 2026-02-08 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-created_at', 'id'], 'verbose_name': '应聘记录', 'verbose_name_plural': '应聘记录'},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['order', 'id'], 'verbose_name': '岗位', 'verbose_name_plural': '岗位'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['order', 'id'], 'verbose_name': '地区', 'verbose_name_plural': '地区'},
        ),
        migrations.AlterModelOptions(
            name='regionfield',
            options={'ordering': ['order', 'id'], 'verbose_name': '地区字段', 'verbose_name_plural': '地区字段'},
        ),
        migrations.AddField(
            model_name='application',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='年龄'),
        ),
        migrations.AddField(
            model_name='application',
            name='apply_company',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='应聘公司'),
        ),
        migrations.AddField(
            model_name='application',
            name='available_date',
            field=models.DateField(blank=True, null=True, verbose_name='能上岗日期'),
        ),
        migrations.AddField(
            model_name='application',
            name='birth_month',
            field=models.DateField(blank=True, null=True, verbose_name='出生年月'),
        ),
        migrations.AddField(
            model_name='application',
            name='current_address',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='现住地址'),
        ),
        migrations.AddField(
            model_name='application',
            name='diploma_number',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='毕业证编号'),
        ),
        migrations.AddField(
            model_name='application',
            name='education_history',
            field=models.JSONField(blank=True, default=list, verbose_name='教育培训经历'),
        ),
        migrations.AddField(
            model_name='application',
            name='education_level',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='学历'),
        ),
        migrations.AddField(
            model_name='application',
            name='emergency_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='紧急联系人姓名'),
        ),
        migrations.AddField(
            model_name='application',
            name='emergency_phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='紧急联系人手机号'),
        ),
        migrations.AddField(
            model_name='application',
            name='ethnicity',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='民族'),
        ),
        migrations.AddField(
            model_name='application',
            name='expected_salary',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='期望薪资'),
        ),
        migrations.AddField(
            model_name='application',
            name='family_members',
            field=models.JSONField(blank=True, default=list, verbose_name='家庭成员'),
        ),
        migrations.AddField(
            model_name='application',
            name='graduate_school',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='毕业院校'),
        ),
        migrations.AddField(
            model_name='application',
            name='graduation_date',
            field=models.DateField(blank=True, null=True, verbose_name='毕业时间'),
        ),
        migrations.AddField(
            model_name='application',
            name='health_status',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='健康情况'),
        ),
        migrations.AddField(
            model_name='application',
            name='height_cm',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='身高(cm)'),
        ),
        migrations.AddField(
            model_name='application',
            name='hobbies',
            field=models.TextField(blank=True, default='', verbose_name='兴趣爱好'),
        ),
        migrations.AddField(
            model_name='application',
            name='hukou_address',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='户口所在地'),
        ),
        migrations.AddField(
            model_name='application',
            name='hukou_type',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='户口性质'),
        ),
        migrations.AddField(
            model_name='application',
            name='id_number',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='身份证号'),
        ),
        migrations.AddField(
            model_name='application',
            name='major',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='专业'),
        ),
        migrations.AddField(
            model_name='application',
            name='marital_status',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='婚姻情况'),
        ),
        migrations.AddField(
            model_name='application',
            name='native_place',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='籍贯'),
        ),
        migrations.AddField(
            model_name='application',
            name='political_status',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='政治面貌'),
        ),
        migrations.AddField(
            model_name='application',
            name='qq',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='QQ'),
        ),
        migrations.AddField(
            model_name='application',
            name='recruitment_source',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='招聘来源'),
        ),
        migrations.AddField(
            model_name='application',
            name='referrer_company',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='介绍人单位'),
        ),
        migrations.AddField(
            model_name='application',
            name='referrer_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='介绍人姓名'),
        ),
        migrations.AddField(
            model_name='application',
            name='referrer_relation',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='介绍人关系'),
        ),
        migrations.AddField(
            model_name='application',
            name='self_evaluation',
            field=models.TextField(blank=True, default='', verbose_name='自我评价'),
        ),
        migrations.AddField(
            model_name='application',
            name='title_cert',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='职称证书'),
        ),
        migrations.AddField(
            model_name='application',
            name='weight_kg',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='体重(kg)'),
        ),
        migrations.AddField(
            model_name='application',
            name='work_history',
            field=models.JSONField(blank=True, default=list, verbose_name='工作经历'),
        ),
        migrations.AlterField(
            model_name='application',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='提交时间'),
        ),
        migrations.AlterField(
            model_name='application',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='application',
            name='extra_fields',
            field=models.JSONField(blank=True, default=dict, verbose_name='扩展字段'),
        ),
        migrations.AlterField(
            model_name='application',
            name='gender',
            field=models.CharField(max_length=20, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='application',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='application.job', verbose_name='岗位'),
        ),
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(max_length=50, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='application',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='application',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='application.region', verbose_name='地区'),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True, verbose_name='岗位描述'),
        ),
        migrations.AlterField(
            model_name='job',
            name='education',
            field=models.CharField(blank=True, max_length=50, verbose_name='学历要求'),
        ),
        migrations.AlterField(
            model_name='job',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='启用'),
        ),
        migrations.AlterField(
            model_name='job',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='job',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='application.region', verbose_name='地区'),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.CharField(blank=True, max_length=100, verbose_name='薪资范围'),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=100, verbose_name='岗位名称'),
        ),
        migrations.AlterField(
            model_name='region',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='地区编码'),
        ),
        migrations.AlterField(
            model_name='region',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='启用'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='地区名称'),
        ),
        migrations.AlterField(
            model_name='region',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='regionfield',
            name='field_type',
            field=models.CharField(choices=[('text', '文本'), ('select', '下拉'), ('number', '数字'), ('date', '日期')], default='text', max_length=20, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='regionfield',
            name='key',
            field=models.CharField(max_length=50, verbose_name='字段编码'),
        ),
        migrations.AlterField(
            model_name='regionfield',
            name='label',
            field=models.CharField(max_length=50, verbose_name='字段显示名'),
        ),
        migrations.AlterField(
            model_name='regionfield',
            name='options',
            field=models.JSONField(blank=True, null=True, verbose_name='选项'),
        ),
        migrations.AlterField(
            model_name='regionfield',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='regionfield',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='application.region', verbose_name='地区'),
        ),
        migrations.AlterField(
            model_name='regionfield',
            name='required',
            field=models.BooleanField(default=False, verbose_name='必填'),
        ),
        migrations.CreateModel(
            name='ApplicationAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('photo', '个人照片'), ('id_front', '身份证正面'), ('id_back', '身份证反面'), ('diploma', '毕业证'), ('degree', '学位证'), ('resume', '个人简历'), ('criminal', '无犯罪证明'), ('credit', '个人信用报告'), ('other', '其他相关附件')], max_length=30, verbose_name='附件类型')),
                ('file', models.FileField(upload_to='attachments/%Y/%m/', verbose_name='文件')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='application.application')),
            ],
            options={
                'verbose_name': '附件',
                'verbose_name_plural': '附件',
                'ordering': ['-created_at', 'id'],
            },
        ),
    ]
