# Generated by Django 4.2.28 on 2026-02-08 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_alter_application_options_alter_job_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='apply_region',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='应聘区域'),
        ),
        migrations.AddField(
            model_name='application',
            name='education_period',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='最高学历起止时间'),
        ),
        migrations.AddField(
            model_name='application',
            name='recruit_type',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='招聘类型'),
        ),
        migrations.AlterField(
            model_name='application',
            name='education_level',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='最高学历'),
        ),
    ]
