# Generated by Django 4.2.28 on 2026-02-13 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_interviewcandidate_result_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewRoundRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_no', models.PositiveSmallIntegerField(verbose_name='面试轮次')),
                ('interview_at', models.DateTimeField(blank=True, null=True, verbose_name='面试时间')),
                ('interviewer', models.CharField(blank=True, default='', max_length=100, verbose_name='面试官')),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='面试评分')),
                ('result', models.CharField(blank=True, choices=[('待定', '待定'), ('进入下一轮', '进入下一轮'), ('通过', '通过'), ('淘汰', '淘汰')], default='', max_length=20, verbose_name='面试结果')),
                ('result_note', models.TextField(blank=True, default='', verbose_name='结果评语')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_records', to='application.interviewcandidate', verbose_name='拟面试人员')),
            ],
            options={
                'verbose_name': '面试轮次记录',
                'verbose_name_plural': '面试轮次记录',
                'ordering': ['round_no', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='interviewroundrecord',
            constraint=models.UniqueConstraint(fields=('candidate', 'round_no'), name='uniq_interview_candidate_round_no'),
        ),
    ]
