# Generated by Django 4.2.28 on 2026-02-14 05:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0009_interviewroundrecord_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_username', models.CharField(blank=True, default='', max_length=150, verbose_name='操作账号')),
                ('operator_role', models.CharField(blank=True, default='', max_length=50, verbose_name='操作角色')),
                ('operator_region_name', models.CharField(blank=True, default='', max_length=50, verbose_name='操作地区')),
                ('module', models.CharField(max_length=50, verbose_name='模块')),
                ('action', models.CharField(max_length=80, verbose_name='动作')),
                ('target_type', models.CharField(blank=True, default='', max_length=50, verbose_name='对象类型')),
                ('target_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='对象ID')),
                ('target_label', models.CharField(blank=True, default='', max_length=200, verbose_name='对象名称')),
                ('result', models.CharField(choices=[('success', '成功'), ('failed', '失败')], default='success', max_length=20, verbose_name='结果')),
                ('summary', models.CharField(blank=True, default='', max_length=255, verbose_name='摘要')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='详情')),
                ('request_id', models.CharField(blank=True, default='', max_length=64, verbose_name='请求链路ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_logs', to='application.application', verbose_name='关联应聘记录')),
                ('interview_candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_logs', to='application.interviewcandidate', verbose_name='关联拟面试记录')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_logs', to='application.region', verbose_name='所属地区')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['created_at'], name='oplog_created'), models.Index(fields=['module', 'action'], name='oplog_mod_act'), models.Index(fields=['result'], name='oplog_result'), models.Index(fields=['operator_username'], name='oplog_operator'), models.Index(fields=['application'], name='oplog_app'), models.Index(fields=['region'], name='oplog_region')],
            },
        ),
    ]
