# Generated by Django 5.2.5 on 2026-02-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0010_operationlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="OperationLogArchive",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source_log_id", models.PositiveIntegerField(unique=True, verbose_name="原日志ID")),
                ("operator_username", models.CharField(blank=True, default="", max_length=150, verbose_name="操作账号")),
                ("operator_role", models.CharField(blank=True, default="", max_length=50, verbose_name="操作角色")),
                ("operator_region_name", models.CharField(blank=True, default="", max_length=50, verbose_name="操作地区")),
                ("module", models.CharField(max_length=50, verbose_name="模块")),
                ("action", models.CharField(max_length=80, verbose_name="动作")),
                ("target_type", models.CharField(blank=True, default="", max_length=50, verbose_name="对象类型")),
                ("target_id", models.PositiveIntegerField(blank=True, null=True, verbose_name="对象ID")),
                ("target_label", models.CharField(blank=True, default="", max_length=200, verbose_name="对象名称")),
                (
                    "result",
                    models.CharField(
                        choices=[("success", "成功"), ("failed", "失败")],
                        default="success",
                        max_length=20,
                        verbose_name="结果",
                    ),
                ),
                ("summary", models.CharField(blank=True, default="", max_length=255, verbose_name="摘要")),
                ("details", models.JSONField(blank=True, default=dict, verbose_name="详情")),
                ("request_id", models.CharField(blank=True, default="", max_length=64, verbose_name="请求链路ID")),
                ("created_at", models.DateTimeField(verbose_name="记录时间")),
                ("archived_at", models.DateTimeField(auto_now_add=True, verbose_name="归档时间")),
            ],
            options={
                "verbose_name": "操作日志归档",
                "verbose_name_plural": "操作日志归档",
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
