# Generated by Django 4.2.28 on 2026-02-14 08:11

import application.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_operationlogarchive'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='attachment_token',
            field=models.CharField(db_index=True, default=application.models.generate_attachment_token, editable=False, max_length=48, verbose_name='附件令牌'),
        ),
    ]
