# Generated by Django 4.2.28 on 2026-02-16 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_job_deleted_at_job_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewcandidate',
            name='hired_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='确认入职时间'),
        ),
        migrations.AddField(
            model_name='interviewcandidate',
            name='is_hired',
            field=models.BooleanField(default=False, verbose_name='已确认入职'),
        ),
    ]
