# Generated by Django 4.2.11 on 2026-02-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0015_interviewcandidate_sms_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewcandidate",
            name="interviewer_scores",
            field=models.JSONField(blank=True, default=list, verbose_name="面试官评分明细"),
        ),
        migrations.AddField(
            model_name="interviewcandidate",
            name="interviewers",
            field=models.JSONField(blank=True, default=list, verbose_name="面试官列表"),
        ),
        migrations.AddField(
            model_name="interviewroundrecord",
            name="interviewer_scores",
            field=models.JSONField(blank=True, default=list, verbose_name="面试官评分明细"),
        ),
        migrations.AddField(
            model_name="interviewroundrecord",
            name="interviewers",
            field=models.JSONField(blank=True, default=list, verbose_name="面试官列表"),
        ),
    ]
