# Generated by Django 4.2.11 on 2026-02-27 00:00

from django.db import migrations, models


def sync_offer_status_for_existing_rows(apps, schema_editor):
    InterviewCandidate = apps.get_model("application", "InterviewCandidate")
    InterviewCandidate.objects.filter(is_hired=True).update(offer_status="confirmed_hire")


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0016_interview_multi_interviewer_scores"),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewcandidate",
            name="offer_status",
            field=models.CharField(
                choices=[
                    ("pending_hire", "待确认入职"),
                    ("confirmed_hire", "已确认入职"),
                    ("offer_rejected", "拒绝offer"),
                ],
                default="pending_hire",
                max_length=30,
                verbose_name="Offer状态",
            ),
        ),
        migrations.RunPython(sync_offer_status_for_existing_rows, migrations.RunPython.noop),
    ]
