# Generated by Django 4.2.11 on 2026-02-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0017_interviewcandidate_offer_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interviewcandidate",
            name="offer_status",
            field=models.CharField(
                choices=[
                    ("pending_hire", "待发offer"),
                    ("offer_issued", "已发offer"),
                    ("confirmed_hire", "待确认入职"),
                    ("offer_rejected", "拒绝offer"),
                ],
                default="pending_hire",
                max_length=30,
                verbose_name="Offer状态",
            ),
        ),
    ]