# Generated by Django 4.2.28 on 2026-02-28 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0018_alter_interviewcandidate_offer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewcandidate',
            name='oa_push_error_code',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='OA推送错误码'),
        ),
        migrations.AddField(
            model_name='interviewcandidate',
            name='oa_push_error_message',
            field=models.TextField(blank=True, default='', verbose_name='OA推送失败原因'),
        ),
        migrations.AddField(
            model_name='interviewcandidate',
            name='oa_push_last_attempt_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='OA推送最近尝试时间'),
        ),
        migrations.AddField(
            model_name='interviewcandidate',
            name='oa_push_oa_code',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='OA返回码'),
        ),
        migrations.AddField(
            model_name='interviewcandidate',
            name='oa_push_oa_message',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='OA返回信息'),
        ),
        migrations.AddField(
            model_name='interviewcandidate',
            name='oa_push_payload_snapshot',
            field=models.JSONField(blank=True, default=dict, verbose_name='OA推送请求快照'),
        ),
        migrations.AddField(
            model_name='interviewcandidate',
            name='oa_push_request_id',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='OA流程请求ID'),
        ),
        migrations.AddField(
            model_name='interviewcandidate',
            name='oa_push_retry_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='OA推送重试次数'),
        ),
        migrations.AddField(
            model_name='interviewcandidate',
            name='oa_push_status',
            field=models.CharField(choices=[('idle', '未推送'), ('pending', '推送中'), ('success', '推送成功'), ('failed', '推送失败')], default='idle', max_length=20, verbose_name='OA推送状态'),
        ),
        migrations.AddField(
            model_name='interviewcandidate',
            name='oa_push_success_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='OA推送成功时间'),
        ),
    ]
