# Generated by Django 4.2.28 on 2026-03-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0019_interviewcandidate_oa_push_error_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationattachment",
            name="category",
            field=models.CharField(
                choices=[
                    ("photo", "个人照片"),
                    ("id_front", "身份证正面"),
                    ("id_back", "身份证反面"),
                    ("diploma", "毕业证"),
                    ("degree", "学位证"),
                    ("resume", "个人简历"),
                    ("criminal", "无犯罪证明"),
                    ("credit", "个人信用报告"),
                    ("other", "其他相关附件"),
                    ("interview_extra", "面试补充材料"),
                ],
                max_length=30,
                verbose_name="附件类型",
            ),
        ),
    ]
