from django.urls import path

from .views import (
    AdminApplicationDetailView,
    AdminApplicationListView,
    AdminJobDetailView,
    AdminJobListView,
    AdminRegionDetailView,
    AdminRegionFieldDetailView,
    AdminRegionFieldListView,
    AdminRegionListView,
    AdminUserDetailView,
    AdminUserListView,
    AdminUserPasswordView,
    ChangePasswordView,
    HealthCheckView,
    ApplicationAttachmentListCreateView,
    ApplicationCreateView,
    ApplicationSubmitView,
    JobDetailView,
    JobListView,
    LoginView,
    MeView,
    MockOAView,
    RegisterView,
    RegionListView,
)

urlpatterns = [
    path("health/", HealthCheckView.as_view(), name="health"),
    path("regions/", RegionListView.as_view(), name="regions"),
    path("jobs/", JobListView.as_view(), name="jobs"),
    path("jobs/<int:pk>/", JobDetailView.as_view(), name="job-detail"),
    path("applications/", ApplicationCreateView.as_view(), name="application-create"),
    path(
        "applications/<int:pk>/attachments/",
        ApplicationAttachmentListCreateView.as_view(),
        name="application-attachments",
    ),
    path("application/submit/", ApplicationSubmitView.as_view(), name="application-submit"),
    path("application/mock-oa/", MockOAView.as_view(), name="mock-oa"),
    path("auth/register/", RegisterView.as_view(), name="auth-register"),
    path("auth/login/", LoginView.as_view(), name="auth-login"),
    path("auth/me/", MeView.as_view(), name="auth-me"),
    path("auth/password/", ChangePasswordView.as_view(), name="auth-password"),
    path("admin/regions/", AdminRegionListView.as_view(), name="admin-regions"),
    path("admin/regions/<int:pk>/", AdminRegionDetailView.as_view(), name="admin-region-detail"),
    path("admin/region-fields/", AdminRegionFieldListView.as_view(), name="admin-region-fields"),
    path(
        "admin/region-fields/<int:pk>/",
        AdminRegionFieldDetailView.as_view(),
        name="admin-region-field-detail",
    ),
    path("admin/jobs/", AdminJobListView.as_view(), name="admin-jobs"),
    path("admin/jobs/<int:pk>/", AdminJobDetailView.as_view(), name="admin-job-detail"),
    path("admin/applications/", AdminApplicationListView.as_view(), name="admin-applications"),
    path(
        "admin/applications/<int:pk>/",
        AdminApplicationDetailView.as_view(),
        name="admin-application-detail",
    ),
    path("admin/users/", AdminUserListView.as_view(), name="admin-users"),
    path("admin/users/<int:pk>/", AdminUserDetailView.as_view(), name="admin-user-detail"),
    path(
        "admin/users/<int:pk>/password/",
        AdminUserPasswordView.as_view(),
        name="admin-user-password",
    ),
]
