"""application 模块路由定义，将接口路径映射到视图。"""
from django.urls import path

from .views import (
    AdminApplicationDetailView,
    AdminApplicationListView,
    AdminInterviewCandidateBatchAddView,
    AdminInterviewCandidateBatchRemoveView,
    AdminInterviewCandidateCancelScheduleView,
    AdminInterviewCandidateDetailView,
    AdminInterviewCandidateListView,
    AdminInterviewMetaView,
    AdminOperationLogDetailView,
    AdminOperationLogListView,
    AdminOperationLogMetaView,
    AdminPassedCandidateListView,
    AdminPassedCandidateBatchConfirmHireView,
    AdminPassedCandidateBatchConfirmOnboardView,
    AdminPassedCandidateOfferStatusView,
    AdminPassedCandidateRetryOAPushView,
    AdminTalentPoolCandidateListView,
    AdminTalentPoolCandidateBatchAddView,
    AdminTalentPoolCandidateBatchToInterviewView,
    AdminInterviewCandidateResultView,
    AdminInterviewCandidateResendSmsView,
    AdminInterviewCandidateScheduleView,
    AdminJobDetailView,
    AdminJobBatchStatusView,
    AdminJobListView,
    AdminRegionDetailView,
    AdminRegionFieldDetailView,
    AdminRegionFieldListView,
    AdminRegionListView,
    AdminUserDetailView,
    AdminUserListView,
    AdminUserPasswordView,
    ChangePasswordView,
    HealthCheckView,
    ApplicationAttachmentListCreateView,
    ApplicationCreateView,
    ApplicationDiscardView,
    ApplicationSubmitView,
    JobDetailView,
    JobListView,
    LoginView,
    LogoutView,
    MeView,
    RegisterView,
    RegionListView,
)

urlpatterns = [
    path("health/", HealthCheckView.as_view(), name="health"),
    path("regions/", RegionListView.as_view(), name="regions"),
    path("jobs/", JobListView.as_view(), name="jobs"),
    path("jobs/<int:pk>/", JobDetailView.as_view(), name="job-detail"),
    path("applications/", ApplicationCreateView.as_view(), name="application-create"),
    path(
        "applications/<int:pk>/attachments/",
        ApplicationAttachmentListCreateView.as_view(),
        name="application-attachments",
    ),
    path(
        "applications/<int:pk>/discard/",
        ApplicationDiscardView.as_view(),
        name="application-discard",
    ),
    path("application/submit/", ApplicationSubmitView.as_view(), name="application-submit"),
    path("auth/register/", RegisterView.as_view(), name="auth-register"),
    path("auth/login/", LoginView.as_view(), name="auth-login"),
    path("auth/logout/", LogoutView.as_view(), name="auth-logout"),
    path("auth/me/", MeView.as_view(), name="auth-me"),
    path("auth/password/", ChangePasswordView.as_view(), name="auth-password"),
    path("admin/regions/", AdminRegionListView.as_view(), name="admin-regions"),
    path("admin/regions/<int:pk>/", AdminRegionDetailView.as_view(), name="admin-region-detail"),
    path("admin/region-fields/", AdminRegionFieldListView.as_view(), name="admin-region-fields"),
    path(
        "admin/region-fields/<int:pk>/",
        AdminRegionFieldDetailView.as_view(),
        name="admin-region-field-detail",
    ),
    path("admin/jobs/", AdminJobListView.as_view(), name="admin-jobs"),
    path("admin/jobs/batch-status/", AdminJobBatchStatusView.as_view(), name="admin-jobs-batch-status"),
    path("admin/jobs/<int:pk>/", AdminJobDetailView.as_view(), name="admin-job-detail"),
    path("admin/applications/", AdminApplicationListView.as_view(), name="admin-applications"),
    path(
        "admin/applications/<int:pk>/",
        AdminApplicationDetailView.as_view(),
        name="admin-application-detail",
    ),
    path(
        "admin/interview-candidates/",
        AdminInterviewCandidateListView.as_view(),
        name="admin-interview-candidates",
    ),
    path(
        "admin/interview-meta/",
        AdminInterviewMetaView.as_view(),
        name="admin-interview-meta",
    ),
    path(
        "admin/operation-logs/",
        AdminOperationLogListView.as_view(),
        name="admin-operation-logs",
    ),
    path(
        "admin/operation-logs/<int:pk>/",
        AdminOperationLogDetailView.as_view(),
        name="admin-operation-log-detail",
    ),
    path(
        "admin/operation-logs/meta/",
        AdminOperationLogMetaView.as_view(),
        name="admin-operation-logs-meta",
    ),
    path(
        "admin/passed-candidates/",
        AdminPassedCandidateListView.as_view(),
        name="admin-passed-candidates",
    ),
    path(
        "admin/passed-candidates/batch-confirm-hire/",
        AdminPassedCandidateBatchConfirmHireView.as_view(),
        name="admin-passed-candidates-batch-confirm-hire",
    ),
    path(
        "admin/passed-candidates/batch-confirm-onboard/",
        AdminPassedCandidateBatchConfirmOnboardView.as_view(),
        name="admin-passed-candidates-batch-confirm-onboard",
    ),
    path(
        "admin/passed-candidates/<int:pk>/offer-status/",
        AdminPassedCandidateOfferStatusView.as_view(),
        name="admin-passed-candidate-offer-status",
    ),
    path(
        "admin/passed-candidates/<int:pk>/retry-oa-push/",
        AdminPassedCandidateRetryOAPushView.as_view(),
        name="admin-passed-candidate-retry-oa-push",
    ),
    path(
        "admin/talent-pool-candidates/",
        AdminTalentPoolCandidateListView.as_view(),
        name="admin-talent-pool-candidates",
    ),
    path(
        "admin/talent-pool-candidates/batch-add/",
        AdminTalentPoolCandidateBatchAddView.as_view(),
        name="admin-talent-pool-candidates-batch-add",
    ),
    path(
        "admin/talent-pool-candidates/batch-to-interview/",
        AdminTalentPoolCandidateBatchToInterviewView.as_view(),
        name="admin-talent-pool-candidates-batch-to-interview",
    ),
    path(
        "admin/interview-candidates/<int:pk>/",
        AdminInterviewCandidateDetailView.as_view(),
        name="admin-interview-candidate-detail",
    ),
    path(
        "admin/interview-candidates/<int:pk>/schedule/",
        AdminInterviewCandidateScheduleView.as_view(),
        name="admin-interview-candidate-schedule",
    ),
    path(
        "admin/interview-candidates/<int:pk>/cancel-schedule/",
        AdminInterviewCandidateCancelScheduleView.as_view(),
        name="admin-interview-candidate-cancel-schedule",
    ),
    path(
        "admin/interview-candidates/<int:pk>/result/",
        AdminInterviewCandidateResultView.as_view(),
        name="admin-interview-candidate-result",
    ),
    path(
        "admin/interview-candidates/<int:pk>/resend-sms/",
        AdminInterviewCandidateResendSmsView.as_view(),
        name="admin-interview-candidate-resend-sms",
    ),
    path(
        "admin/interview-candidates/batch-add/",
        AdminInterviewCandidateBatchAddView.as_view(),
        name="admin-interview-candidates-batch-add",
    ),
    path(
        "admin/interview-candidates/batch-remove/",
        AdminInterviewCandidateBatchRemoveView.as_view(),
        name="admin-interview-candidates-batch-remove",
    ),
    path("admin/users/", AdminUserListView.as_view(), name="admin-users"),
    path("admin/users/<int:pk>/", AdminUserDetailView.as_view(), name="admin-user-detail"),
    path(
        "admin/users/<int:pk>/password/",
        AdminUserPasswordView.as_view(),
        name="admin-user-password",
    ),
]
